/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv HCA_A_GT12935004
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv HCA_A_GT12935005
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv HCA_A_GT12935007
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7426907
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7693757
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7693758
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7693759
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7693761
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7714149
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7717783
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7717787
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7718976
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv FCA_gut9456322
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S8001867
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S8123915
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv WTDAtest7844013
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv WTDAtest7844014
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv WTDAtest7844018
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv WTDAtest7844020
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv WTDAtest7844023
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4861STDY7135914
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4861STDY7135915
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S7255679
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv scrEXT019
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv scrEXT025
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv HCA_A_GT12934998
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv HCA_A_GT12935002
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Pan_T7917821
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Pan_T7980366
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Pan_T7980368
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7321513
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7426904
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7447825
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7693762
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7702680
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7923744
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv FCA_gut8015057
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S7985389
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S7985390
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S7985391
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S7985393
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S7985395
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S8000483
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S8000515
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S8001905
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S8123911
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S8123913
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S8159185
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S8159189
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S8159194
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv WTDAtest7770717
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv WTDAtest7770719
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4861STDY7135911
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4861STDY7135917
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4861STDY7208410
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4861STDY7208413
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4861STDY7208414
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4861STDY7208416
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Human_colon_16S7255675
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv Pan_T7935489
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM5101013
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM5101018
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv scrEXT014
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM3972012
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM3972023
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM3972027
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv PT-61_2
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv PT-64_1
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv PTG65_1
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM4904136
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM3214203
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM3587008
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM3587009
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM3587013
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM5005044
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM5005054
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM5005056
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM5177036
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv HT-232_stomach_antrum
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv HT228-fetal-colon
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7933270
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv 4918STDY7982703
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv scrEXT002
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv scrEXT009
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv scrEXT013
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv scrEXT016
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv scrEXT022
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv scrEXT027
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv scrEXT031
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM3214201
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM3433582
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM5101014
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM4546325
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py --force --rerun-cb metadata/cellbender_rerun_samples.results.tsv metadata/sample_metadata.csv GSM4546327
