/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4600896
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4600897
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HCA_A_GT12934997
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HCA_A_GT12934998
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HCA_A_GT12934999
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HCA_A_GT12935000
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HCA_A_GT12935002
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HCA_A_GT12935004
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HCA_A_GT12935005
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HCA_A_GT12935007
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5683602
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5464615
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5464616
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5464617
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5464618
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7917816
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7917821
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7917827
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7935490
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7980366
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7980368
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7991584
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7991585
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7991586
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T8010319
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T8010320
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7274839
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7317585
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7317586
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7317587
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7321513
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7321514
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7321515
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7333456
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7389431
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7421297
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7421298
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7421299
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7426904
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7426905
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7426906
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7426907
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7426908
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7426909
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7447825
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7693757
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7693758
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7693759
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7693760
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7693761
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7693762
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7693763
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7702679
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7702680
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7714149
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7714150
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7717783
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7717784
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7717785
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7717787
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7717788
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7717789
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7718972
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7718973
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7718974
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7718975
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7718976
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7718977
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7844898
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7844899
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7923744
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv FCA_gut8015057
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv FCA_gut8015058
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv FCA_gut8015059
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv FCA_gut8015060
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv FCA_gut8015061
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv FCA_gut9456313
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv FCA_gut9456316
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv FCA_gut9456319
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv FCA_gut9456322
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv FCA_gut9456325
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv FCA_gut9456326
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7985389
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7985390
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7985391
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7985392
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7985393
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7985394
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7985395
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000471
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000473
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000475
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000477
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000479
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000481
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000483
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000484
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000487
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000489
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000491
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000493
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000511
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000513
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8000515
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001863
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001865
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001867
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001869
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001871
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001873
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001875
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001878
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001879
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001881
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001883
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001885
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001903
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001905
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8001907
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002566
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002573
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002574
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002581
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002582
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002623
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002624
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002625
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002626
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002627
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002628
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002629
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8002630
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8117828
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8117829
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8117830
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8117831
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123908
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123909
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123910
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123911
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123912
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123913
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123915
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123916
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123917
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123918
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123919
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123920
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8123921
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159182
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159183
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159184
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159185
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159186
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159187
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159188
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159189
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159190
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159191
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159192
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159193
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S8159194
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7770716
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7770717
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7770718
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7770719
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844013
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844014
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844015
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844016
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844017
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844018
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844019
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844020
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844021
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844022
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844023
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844024
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844025
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844026
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844027
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844028
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844029
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv WTDAtest7844030
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4850580
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4850583
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4850586
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4850588
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4850590
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 5-Int-Fresh-Unsorted
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 6-Int-Fresh-Sorted
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-172-d127-Duo-1
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-172-d127-Duo-2
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-184-d85-duo
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-234-Duo
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-236_day132_duo
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-236_day132_ileum
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-243_small-intestine
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-260-proximal-SI_day-59
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-274_fetal_duo_d72
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT228-fetal-duodenum
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3584928
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3584929
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3584930
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3584931
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3584932
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3584933
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4766840
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4766846
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4766839
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4766845
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4766842
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4766844
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4766848
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7135911
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7135912
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7135913
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7135914
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7135915
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7135916
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7135917
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7135918
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7208410
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7208411
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7208412
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7208413
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7208414
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7208415
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7208416
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4861STDY7208417
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7255675
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7255676
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7255677
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7255678
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7255679
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7255680
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7255681
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Human_colon_16S7255682
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7935487
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7935488
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7935489
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv Pan_T7935494
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101013
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101018
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101021
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101024
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546300
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546302
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546304
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546306
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546308
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546310
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546312
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546314
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546316
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546318
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546320
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546322
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546324
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546326
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546328
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546330
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546332
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546334
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546336
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546338
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546340
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546341
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546343
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546345
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546347
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546348
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546349
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546350
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546351
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3140593
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3140594
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT003
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT011
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT014
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT017
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT020
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT023
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT026
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT029
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT032
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3486911
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR3245538
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR3245540
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR3245543
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161418
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161427
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161429
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161439
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161445
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161455
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161460
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161473
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161474
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161475
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161477
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161479
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161480
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161482
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161486
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161492
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161495
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161504
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161505
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv ERR4161509
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972010
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972012
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972014
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972015
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972018
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972019
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972021
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972023
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972025
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972027
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972029
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv PT-61_1
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv PT-61_2
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv PT-62_1
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv PT-62_2
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv PT-64_1
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv PT-64_2
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv PTG65_1
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv PTG65_2
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4904134
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4904135
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4904136
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4904137
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4904138
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3214203
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3214206
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3214209
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3214202
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3214205
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3214208
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5525959
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5525960
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5525961
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5525962
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3587008
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3587009
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3587010
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3587011
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3587012
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3587013
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005043
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005044
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005045
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005046
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005047
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005048
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005049
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005050
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005051
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005052
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005053
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005054
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005055
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005056
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5005057
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5177036
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5177037
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5177038
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5177039
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5177040
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5177041
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-185-Adult-duo
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-188-Adult-Duo
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-231_esophagus
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-231_stomach_antrum
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-231_stomach_corpus
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-232_esophagus
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-232_stomach_antrum
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-232_stomach_corpus
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-234-Colon
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-234-Ileum
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-234-Jejunum
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT-236_day132_colon
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT228-fetal-colon
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv HT228-fetal-ileum
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7273964
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7273965
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7901096
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7933270
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7962470
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7982702
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv 4918STDY7982703
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT001
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT002
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT009
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT010
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT012
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT013
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT015
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT016
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT018
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT019
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT021
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT022
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT024
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT025
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT027
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT028
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT030
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv scrEXT031
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3140595
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3140596
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3214201
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3214204
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3214207
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3433578
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3433579
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3433580
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3433581
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3433582
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3433583
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3433584
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972009
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972011
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972013
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972016
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972017
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972020
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972022
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972024
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972026
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972028
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM3972030
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4766841
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4766843
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4766847
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4766849
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101014
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101015
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101016
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101017
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101019
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101020
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101022
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101023
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101025
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5101026
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5525955
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5525956
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5525957
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5525958
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM5525963
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546301
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546303
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546305
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546307
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546309
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546311
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546313
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546315
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546317
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546319
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546321
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546323
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546325
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546327
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546329
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546331
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546333
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546335
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546337
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546339
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546342
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546344
/software/team205/miniconda3/envs/rapids-torch/bin/python pyscript/gather_matrices.py metadata/sample_metadata.csv GSM4546346
